version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Use pull requests labeled "dependencies" for npm updates
    labels:
      - "dependencies"
    # Ignore major updates for production dependencies
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Only update development dependencies (except for major versions)
    groups:
      development-dependencies:
        dependency-type: "development"
      
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Use pull requests labeled "github-actions" for GitHub Actions updates
    labels:
      - "github-actions"
